export const FETCH_CHECKS = {
    FAILURE: 'CHECKS/FETCH_FAILURE',
    START: 'CHECKS/FETCH_START',
    SUCCESS: 'CHECKS/FETCH_SUCCESS',
};

export const UPDATE_CHECKS = {
    FAILURE: 'CHECKS/UPDATE_FAILURE',
    START: 'CHECKS/UPDATE_START',
    SUCCESS: 'CHECKS/UPDATE_SUCCESS',
};
